SurveyManagement/Models/Domain/Survey.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace SurveyManagement.Models.Domain
{
    public class Survey
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; private set; }
        [Required(ErrorMessage = "Вы не ввели название опросника")]
        [StringLength(100,ErrorMessage = "Название опросника не должно превышать 100 символов")]
        [Display(Name = "Название опросника")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Вы не ввели имя создателя")]
        [StringLength(40, ErrorMessage = "Имя создателя не должно превышать 40 символов")]
        [Display(Name = "Имя создателя")]
        public string Creator { get; set; }
        [HiddenInput(DisplayValue = false)]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public Survey()
        {
            Date = DateTime.Now;
        }
    }
}

SurveyManagement/Controllers/SurveyController.cs
using Microsoft.AspNetCore.Mvc;
using SurveyManagement.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SurveyManagement.Controllers
{

    public class SurveyController : Controller
    {
        private readonly Repository<Models.Domain.Survey> _rep;

        public SurveyController(Repository<Models.Domain.Survey> rep)
        {
            _rep = rep;
        }

        public IActionResult Survey(int id)
        {
            ViewBag.survey = _rep.FindById(id);
            return View(_rep.FindQuestionsWithAnswers(id));
        }

        [HttpGet]
        public IActionResult CreateSurvey()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateSurvey(Models.Domain.Survey new_survey)
        {
            var listNames = _rep.GetAll();
            foreach (var a in listNames)
            {
                if (new_survey.Name == a.Name)
                {
                    ModelState.AddModelError("Name", "Опросник с таким названием уже существует");
                }
            }
            if (ModelState.IsValid)
            {
                _rep.Create(new_survey);
                return Redirect(String.Format("~/View/Survey/{0}", new_survey.Id));
            }
            return View();
        }



        [Route("survey")]
        public ActionResult<IList<Models.Domain.Survey>> Get()
        {
            return new OkObjectResult(_rep.GetAll());
        }

        [HttpGet("/survey/{id}")]
        public ActionResult GetSingleSurvey(int id)
        {
            return new OkObjectResult(_rep.FindById(id));
        }

        [HttpGet("/QuestionsWithAnswers/{id}")]
        public ActionResult GetSingleQuestionsWithAnswers(int id)
        {
            return new OkObjectResult(_rep.FindQuestionsWithAnswers(id));
        }

        //[HttpPut("/survey/{id}")]
        //public ActionResult EditSurvey(int id)
        //{
        //    var a = _rep.FindById(id);

        //    return new OkObjectResult(_rep.(id));
        //}

        [HttpPost]
        public ActionResult Create(Models.Domain.Survey item)
        {
            _rep.Create(item);

            return Ok();
        }
        [HttpDelete("{id}")]
        public ActionResult Delete([FromRoute] int id)
        {
            var surveys = _rep.FindById(id);
            _rep.Remove(surveys);
            return Ok();
        }

    }
}

SurveyManagement/Controllers/ViewController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SurveyManagement.Models;

namespace SurveyManagement.Controllers
{
    public class ViewController : Controller
    {
        private readonly Repository<Models.Domain.Survey> _rep;
        public ViewController(Repository<Models.Domain.Survey> rep)
        {
            _rep = rep;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_rep.Get());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SurveyManagement/Views/Survey/CreateSurvey.cshtml
@model SurveyManagement.Models.Domain.Survey
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateSurvey</title>
</head>
<body>

    @using (Html.BeginForm("CreateSurvey", "View"))
    {
    <fieldset>

        <h2>Создание опросника</h2>

        <p>
            @Html.LabelFor(x => x.Name)
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(x => x.Name)
        </p>

        <p>
            @Html.LabelFor(x => x.Creator)
            @Html.EditorFor(x => x.Creator)
            @Html.ValidationMessageFor(x => x.Creator)
        </p>

        <br />
        <br />

        <input type="submit" value="Создать" />
    </fieldset>
    }

</body>
</html>

SurveyManagement/Views/Survey/Survey.cshtml
@{
    ViewData["Title"] = "Survey";
}


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Survey</title>
</head>
<body>
    <h2>@ViewBag.survey.Name</h2>
    <div>@ViewBag.survey.Creator</div>
    <br />

    <div>@ViewBag.survey.Date.ToShortDateString()</div>
    <br />
    <br />


    @{
        foreach (var x in Model)
        {
            <div>@x.Questions.Text</div>
            
            <button>@Html.RouteLink("Добавить ответ", new { Controller = "Answer", Action = "CreateAnswer", Id = x.Questions.Id })</button>
            <div>@x.Questions.Comment</div>

            foreach (SurveyManagement.Models.Domain.Answer i in x.Answers)
            {
                @Html.CheckBox(i.Text)
                <label>@i.Text</label>
                <br />
            }
        }

    }
    <div cllas="nav">
        <p>
            <a href="@(ViewBag.survey.Id-1)">Предыдущий опрос</a>
            <a href="@(ViewBag.survey.Id+1)">Следующий опрос</a>
        </p>
    </div>
    <button>@Html.RouteLink("Добавить вопрос", new { Controller = "Questions", Action = "CreateQuestion", Id = ViewBag.survey.Id })</button>

</body>
</html>